# See the pakku.conf(5) manpage

[options]
#UserCacheDir = ${HOME}/.cache/pakku
#TmpDir = /tmp/pakku-${USER}
#PackageOutputDir =
#AurRepo = aur

AurComments
CheckIgnored
#IgnoreArch
PrintAurNotFound
PrintLocalIsNewer
#SudoExec
#ViewNoDefault

#KeepBuildDirOnFailure
#KeepBuiltPackagesOnFailure

#PreserveBuilt = Disabled | Internal | User | Pkgdest
#CleanupAfterInstall = Full

#PreBuildCommand =
#PreferredSudoCommand =
